Repository jonwiseman/LFJ, pull requests merged in 2020-03, with the labels that each got.

#1 Mattbcool
  README.md
  Scripts/bot_controller.py
  Scripts/user_queries.py
Labels: documentation, enhancement

#3 Added help command
  Scripts/bot_controller.py
Labels: enhancement

#5 Game queries
  Scripts/bot_controller.py
  Scripts/game_queries.py
Labels: enhancement

#6 Fixed user update commands
  Scripts/game_queries.py
  Scripts/user_queries.py
Labels: bug
